name: "PR Audit"
description: "Check to see if PR is up to standards"
inputs:
  - response:
      description: "the http response"
      required: true
  - repoOwner:
      required: true
  - repoName:
      required: true
  - pullNumber:
      required: true

  

runs:
  using: 'node16'
  main: 'index.js'