name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - edited
      
  issue_comment:
    types:
      - created
      - edited
      - deleted
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - run: echo " PR has been ${{ github.event_name }} "
  
