name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      
  issue_comment:
    types:
      - created
      - edited
      - deleted
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
        
    steps:
      - name: Fetch Labels
        id: fetch-labels
        uses: actions/github-script@v6
        with: 
          script: return "Hello!"
          result-encoding: string
          
      - name: Print Labels
        run: echo " DING ${{steps.fetch-labels.outputs.result}}"
  
