name: github actions PR test
run-name: Validating PR
on:
  pull_request:
    types: [opened, edited]
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - run: echo " PR has been ${{ GITHUB_EVENT_NAME }} 
  
