name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      
  issue_comment:
    types:
      - created
      - edited
      - deleted
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Labels
        id: fetch-labels
        uses: actions/github-script@v6
        with: 
          script: |
            return github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              });
                    
      - name: Audit Labels
        id: audit
        uses: ./pr-audit-action
        with:
          response: "${{steps.fetch-labels.outputs.result}}"
          repoName: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Results
        uses: actions/github-script@v6
        if: ${{ steps.audit.outputs.error == 'bad-labels' && failure() }}
        with: 
         script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'You need to add either the \"Public Release Notes\" or \"No Release Notes\" label!'
            })