name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      
  issue_comment:
    types:
      - created
      - edited
      - deleted
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
        
    steps:
      - name: Fetch Labels
        id: fetch-labels
        uses: actions/github-script@v6
        with: 
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
          result-encoding: string
          
      - name: Print Labels
        run: echo " DING ${{steps.fetch-labels.outputs.result}}"
  
