name: Github PR Audit

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      
  issue_comment:
    types:
      - created
      - edited
      - deleted
jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with: 
          script: |
            github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            ])
      - name: Get result
        run: echo " DING ${{steps.set-result.outputs.result}}"
  
